version: '3'
volumes: :
    dados:
services:
    db:
        image: postgres:9.6
        volumes:
            #volume dos dados
            
        environment:
            POSTGRES_HOST_AUTH_METHOD: trust
